cd d:

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat

call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat
call D:\JMeterBatchRunner\RMA_TC_001\RMA_TC_00Test.bat